export const DiagramTestData = {
  serializationSettings: { preventDefaults: true },
  snapSettings: { constraints: 3 },
  scrollSettings: { viewPortWidth: 591.984375, viewPortHeight: 1900 },
  layers: [
    {
      id: 'default_layer',
      visible: true,
      lock: false,
      objects: ['tJf0E', 'tJf0EUh3NO', 'tJf0EUh3NOG5NG7'],
      zIndex: 0,
      objectZIndex: 2,
    },
  ],
  nodes: [
    {
      shape: { type: 'Basic' },
      id: 'tJf0E',
      data: {
        id: 'ICU_PATIENT_ROOM',
        title: 'ICU PATIENT ROOM',
        height: 100,
        width: 100,
        offsetX: 100,
        offsetY: 100,
        textColor: 'black',
        fillColor: 'blue',
        strokeWidth: 2,
        strokeColor: 'black',
        borderColor: 'green',
        borderWidth: 10,
      },
      height: 100,
      width: 100,
      offsetX: 208,
      offsetY: 150,
      borderColor: 'blue',
      annotations: [{ id: 'fe74v', content: 'ICU PATIENT ROOM 1' }],
      style: { fill: 'blue', strokeWidth: 3, opacity: 0.5 },
      zIndex: 0,
    },
    {
      shape: { type: 'Basic' },
      id: 'tJf0EUh3NO',
      data: {
        id: 'ICU_PATIENT_ROOM',
        title: 'ICU PATIENT ROOM',
        height: 100,
        width: 100,
        offsetX: 100,
        offsetY: 100,
        textColor: 'black',
        fillColor: 'blue',
        strokeWidth: 2,
        strokeColor: 'black',
        borderColor: 'green',
        borderWidth: 10,
      },
      height: 100,
      width: 100,
      offsetX: 350,
      offsetY: 150,
      borderColor: 'blue',
      annotations: [{ id: 'fe74v', content: 'ICU PATIENT ROOM 2' }],
      style: { fill: 'blue', strokeWidth: 3, opacity: 0.5 },
      zIndex: 1,
    },
    {
      shape: { type: 'Basic' },
      id: 'tJf0EUh3NOG5NG7',
      data: {
        id: 'ICU_PATIENT_ROOM',
        title: 'ICU PATIENT ROOM',
        height: 100,
        width: 100,
        offsetX: 100,
        offsetY: 100,
        textColor: 'black',
        fillColor: 'blue',
        strokeWidth: 2,
        strokeColor: 'black',
        borderColor: 'green',
        borderWidth: 10,
      },
      height: 100,
      width: 100,
      offsetX: 493,
      offsetY: 149,
      borderColor: 'blue',
      annotations: [{ id: 'fe74v', content: 'ICU PATIENT ROOM 3' }],
      style: { fill: 'blue', strokeWidth: 3, opacity: 0.5 },
      zIndex: 2,
    },
  ],
  selectedItems: { width: 0, height: 0 },
};

export const assemblies: any[] = [
  {
    id: '1',
    label: 'Project Construction Site Objects',
    hasChild: true,
    children: [
      { id: '11', parentId: '1', label: 'Construction Area', hasChild: false },
      {
        id: '12',
        parentId: '1',
        label: 'Hazard Waste Disposal Area',
        hasChild: false,
      },
      { id: '13', parentId: '1', label: 'Parking Area', hasChild: false },
    ],
  },
  {
    id: '2',
    label: 'Building Zone Objects',
    nodeType: 'folder',
    hasChild: true,
    children: [
      {
        id: '21',
        parentId: '2',
        label: 'Building Structure',
        nodeType: 'folder',
        hasChild: true,
        children: [
          {
            id: '211',
            parentId: '21',
            label: 'Building Footprint',
            hasChild: false,
          },
        ],
      },
      {
        id: '22',
        parentId: '2',
        label: 'Floor',
        nodeType: 'folder',
        hasChild: true,
        children: [
          { id: '221', parentId: '22', label: 'Floor 1', hasChild: false },
          { id: '222', parentId: '22', label: 'Floor 2', hasChild: false },
          { id: '223', parentId: '22', label: 'Floor 3', hasChild: false },
        ],
      },
      {
        id: '23',
        parentId: '2',
        label: 'Roof',
        nodeType: 'folder',
        hasChild: true,
        children: [
          { id: '231', parentId: '23', label: 'Roof Area', hasChild: false },
        ],
      },
      {
        id: '24',
        parentId: '2',
        label: 'Elevators',
        nodeType: 'folder',
        hasChild: true,
        children: [
          {
            id: '241',
            parentId: '24',
            label: 'Elevator 1 (Visitor Passenger)',
            hasChild: false,
          },
          {
            id: '242',
            parentId: '24',
            label: 'Elevator 2 (Patient)',
            hasChild: false,
          },
          {
            id: '243',
            parentId: '24',
            label: 'Elevator 3 (Cargo)',
            hasChild: false,
          },
        ],
      },
      {
        id: '25',
        parentId: '2',
        label: 'Escalators',
        nodeType: 'folder',
        hasChild: true,
        children: [
          { id: '251', parentId: '25', label: 'Escalator 1', hasChild: false },
          { id: '252', parentId: '25', label: 'Escalator 2', hasChild: false },
        ],
      },
      {
        id: '26',
        parentId: '2',
        label: 'Exit Areas',
        nodeType: 'folder',
        hasChild: true,
        children: [
          { id: '261', parentId: '26', label: 'Exit Area 1', hasChild: false },
          { id: '262', parentId: '26', label: 'Exit Area 2', hasChild: false },
        ],
      },
      {
        id: '27',
        parentId: '2',
        label: 'Mechanical Rooms',
        nodeType: 'folder',
        hasChild: true,
        children: [
          {
            id: '271',
            parentId: '27',
            label: 'Mechanical Room 1',
            hasChild: false,
          },
          {
            id: '272',
            parentId: '27',
            label: 'Mechanical Room 2',
            hasChild: false,
          },
        ],
      },
    ],
  },
  {
    id: '3',
    label: 'Hospital Departments',
    nodeType: 'folder',
    hasChild: true,
    children: [
      {
        id: '31',
        parentId: '3',
        label: 'ICU Department',
        children: [
          {
            id: '311',
            parentId: '31',
            label: 'ICU Patient Room Object',
            hasChild: false,
          },
        ],
      },
    ],
  },
];

export const assembliesV2: any[] = [
  {
    id: '1',
    label: 'Project Construction Site Objects',
    hasChild: true,
  },
  { id: '11', parentId: '1', label: 'Construction Area', hasChild: false },
  {
    id: '12',
    parentId: '1',
    label: 'Hazard Waste Disposal Area',
    hasChild: false,
  },
  { id: '13', parentId: '1', label: 'Parking Area', hasChild: false },
  {
    id: '211',
    parentId: '21',
    label: 'Building Footprint',
    hasChild: false,
  },
  {
    id: '2',
    label: 'Building Zone Objects',
    nodeType: 'folder',
    hasChild: true,
  },
  {
    id: '21',
    parentId: '2',
    label: 'Building Structure',
    nodeType: 'folder',
    hasChild: true,
  },
  {
    id: '22',
    parentId: '2',
    label: 'Floor',
    nodeType: 'folder',
    hasChild: true,
  },
  { id: '221', parentId: '22', label: 'Floor 1', hasChild: false },
  { id: '222', parentId: '22', label: 'Floor 2', hasChild: false },
  { id: '223', parentId: '22', label: 'Floor 3', hasChild: false },
  {
    id: '23',
    parentId: '2',
    label: 'Roof',
    nodeType: 'folder',
    hasChild: true,
  },
  { id: '231', parentId: '23', label: 'Roof Area', hasChild: false },
  {
    id: '24',
    parentId: '2',
    label: 'Elevators',
    nodeType: 'folder',
    hasChild: true,
  },
  {
    id: '241',
    parentId: '24',
    label: 'Elevator 1 (Visitor Passenger)',
    hasChild: false,
  },
  {
    id: '242',
    parentId: '24',
    label: 'Elevator 2 (Patient)',
    hasChild: false,
  },
  {
    id: '243',
    parentId: '24',
    label: 'Elevator 3 (Cargo)',
    hasChild: false,
  },
  {
    id: '25',
    parentId: '2',
    label: 'Escalators',
    nodeType: 'folder',
    hasChild: true,
  },
  { id: '251', parentId: '25', label: 'Escalator 1', hasChild: false },
  { id: '252', parentId: '25', label: 'Escalator 2', hasChild: false },
  {
    id: '26',
    parentId: '2',
    label: 'Exit Areas',
    nodeType: 'folder',
    hasChild: true,
  },
  { id: '261', parentId: '26', label: 'Exit Area 1', hasChild: false },
  { id: '262', parentId: '26', label: 'Exit Area 2', hasChild: false },
  {
    id: '27',
    parentId: '2',
    label: 'Mechanical Rooms',
    nodeType: 'folder',
    hasChild: true,
  },
  {
    id: '271',
    parentId: '27',
    label: 'Mechanical Room 1',
    hasChild: false,
  },
  {
    id: '272',
    parentId: '27',
    label: 'Mechanical Room 2',
    hasChild: false,
  },
  {
    id: '3',
    label: 'Hospital Departments',
    nodeType: 'folder',
    hasChild: true,
  },
  {
    id: '31',
    parentId: '3',
    label: 'ICU Department',
    children: [
      {
        id: '311',
        parentId: '31',
        label: 'ICU Patient Room Object',
        hasChild: false,
      },
    ],
  },
];
