export const DiagramTestData = {
  serializationSettings: { preventDefaults: true },
  snapSettings: { constraints: 3 },
  scrollSettings: { viewPortWidth: 591.984375, viewPortHeight: 1900 },
  layers: [
    {
      id: 'default_layer',
      visible: true,
      lock: false,
      objects: ['tJf0E', 'tJf0EUh3NO', 'tJf0EUh3NOG5NG7'],
      zIndex: 0,
      objectZIndex: 2,
    },
  ],
  nodes: [
    {
      shape: { type: 'Basic' },
      id: 'tJf0E',
      data: {
        id: 'ICU_PATIENT_ROOM',
        title: 'ICU PATIENT ROOM',
        department: 'Department 1',
      },
      height: 100,
      width: 100,
      offsetX: 208,
      offsetY: 150,
      borderColor: 'blue',
      annotations: [{ id: 'fe74v', content: 'ICU PATIENT ROOM 1' }],
      style: { fill: 'blue', strokeWidth: 3, opacity: 0.5 },
      zIndex: 0,
    },
    {
      shape: { type: 'Basic' },
      id: 'tJf0EUh3NO',
      data: {
        id: 'ICU_PATIENT_ROOM',
        title: 'ICU PATIENT ROOM',
        height: 100,
        width: 100,
        offsetX: 100,
        offsetY: 100,
        textColor: 'black',
        fillColor: 'blue',
        strokeWidth: 2,
        strokeColor: 'black',
        borderColor: 'green',
        borderWidth: 10,
      },
      height: 100,
      width: 100,
      offsetX: 350,
      offsetY: 150,
      borderColor: 'blue',
      annotations: [{ id: 'fe74v', content: 'ICU PATIENT ROOM 2' }],
      style: { fill: 'blue', strokeWidth: 3, opacity: 0.5 },
      zIndex: 1,
    },
    {
      shape: { type: 'Basic' },
      id: 'tJf0EUh3NOG5NG7',
      data: {
        id: 'ICU_PATIENT_ROOM',
        title: 'ICU PATIENT ROOM',
        height: 100,
        width: 100,
        offsetX: 100,
        offsetY: 100,
        textColor: 'black',
        fillColor: 'blue',
        strokeWidth: 2,
        strokeColor: 'black',
        borderColor: 'green',
        borderWidth: 10,
      },
      height: 100,
      width: 100,
      offsetX: 493,
      offsetY: 149,
      borderColor: 'blue',
      annotations: [{ id: 'fe74v', content: 'ICU PATIENT ROOM 3' }],
      style: { fill: 'blue', strokeWidth: 3, opacity: 0.5 },
      zIndex: 2,
    },
  ],
  selectedItems: { width: 0, height: 0 },
};
